apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-options: "Replace=true"
    service.beta.kubernetes.io/azure-load-balancer-resource-group: rg-aks-test # replace with your main RG
    service.beta.kubernetes.io/azure-load-balancer-ip: "4.210.194.231"     # replace with Argo CD IP
spec:
  type: LoadBalancer
  loadBalancerIP: "4.210.194.231"
  selector:
    app: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443

